"""empty message

Revision ID: 40aabb13825d
Revises: a3d144a119ea
Create Date: 2021-02-28 11:42:42.922427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40aabb13825d'
down_revision = 'a3d144a119ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rating', sa.Integer(), nullable=False))
    op.alter_column('comment', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('comment', 'rating')
    # ### end Alembic commands ###
