"""empty message

Revision ID: 97283da1ca10
Revises: 8992270608a0
Create Date: 2021-02-25 23:06:02.065951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97283da1ca10'
down_revision = '8992270608a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('image_path', sa.String(length=128), nullable=False))
    op.add_column('book', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('book', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'stock')
    op.drop_column('book', 'rating')
    op.drop_column('book', 'image_path')
    # ### end Alembic commands ###
