"""empty message

Revision ID: a3d144a119ea
Revises: 06be255e049a
Create Date: 2021-02-27 23:16:17.004916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3d144a119ea'
down_revision = '06be255e049a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('book_rental', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('book_rental', 'rental_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('book_rental', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('book_rental_ibfk_1', 'book_rental', type_='foreignkey')
    op.create_foreign_key(None, 'book_rental', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_rental', type_='foreignkey')
    op.create_foreign_key('book_rental_ibfk_1', 'book_rental', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.alter_column('book_rental', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('book_rental', 'rental_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('book_rental', 'book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('comment')
    # ### end Alembic commands ###
