"""empty message

Revision ID: f66264b00dc2
Revises: 97283da1ca10
Create Date: 2021-02-25 23:50:18.748131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66264b00dc2'
down_revision = '97283da1ca10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=64), nullable=False),
    sa.Column('publisher', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
